# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    arm_with_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - base_base_1
      - base_1_shoulder
      - shoulder_upper_arm
      - upper_arm_forearm
      - forearm_wrist_1
      - wrist_1_wrist_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joints:
      - finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
arm_with_gripper_controller:
  ros__parameters:
    joints:
      - base_base_1
      - base_1_shoulder
      - shoulder_upper_arm
      - upper_arm_forearm
      - forearm_wrist_1
      - wrist_1_wrist_2
      - finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity